### PR TITLE
[RFC #3899] feat(lab): experimental Lexical rich-text editor (RichTextEditor + RichTextView)

### PR DESCRIPTION
**Pull request by potatowagon**
> **Draft / RFC-gated.** This accompanies RFC #3899. Per Astryx's contribution protocol, new components land in `@astryxdesign/lab` first and graduate to `@astryxdesign/core` after the Component Specification Protocol. Opening as a Draft to make the RFC concrete — not requesting merge yet.

## What

Adds an experimental **Lexical WYSIWYG rich-text editor** to `@astryxdesign/lab`:

- **`RichTextEditor`** — editable WYSIWYG surface: headings, bulleted/numbered lists, quote, code block, links, bold/italic/underline/strikethrough/inline-code, markdown-shortcut typing, undo/redo history, tab indentation. Wraps the existing `@astryxdesign/core` `Field` for label/description/status/required so it matches `TextInput`/`TextArea` idioms.
- **`RichTextView`** — read-only renderer for serialized editor state.
- **Extension points** — `nodes` and `plugins` props let consumers layer custom nodes (mentions, images) and plugins (toolbars, autolink, hover cards) on top **without forking** the editor.

Styling is 100% StyleX + design tokens — no stylesheet, dark-mode/theming for free. Lexical's theme slots are mapped to StyleX-generated class names via a shared `editorTheme.ts` so the editor and read-only view render identically.

## Why `lab`, and why optional peers

- New components go through the RFC + Component Specification Protocol and land in `lab` first (per the [Contributing guide](https://github.com/facebook/astryx/wiki/Contributing)). `lab` is `@canary`-only, so this never touches a stable release.
- `lexical` and the `@lexical/*` packages are declared as **optional peer dependencies** (`peerDependenciesMeta.*.optional = true`), pinned to `^0.46.0`. Nothing pulls Lexical in unless a consumer imports the editor.
- **`@astryxdesign/core` is untouched** — its zero-runtime-dep promise is intact. (On eventual graduation to core, the plan is a dedicated `./editor` subpath excluded from the barrel so that promise still holds.)

## Version note

Pinned to `lexical ^0.46.0`. `0.47.0` is currently blocked by the repo's `minimumReleaseAge: 10080` (7-day) supply-chain guard — it's <7 days old — so `0.46.0` is the newest installable line.

## Usage

```tsx
// install the optional peers first:
//   pnpm add lexical @lexical/react @lexical/markdown @lexical/link \
//            @lexical/list @lexical/rich-text @lexical/code @lexical/utils
import {RichTextEditor, RichTextView} from '@astryxdesign/lab';

<RichTextEditor
  label="Notes"
  placeholder="Write something…"
  onChange={state => save(JSON.stringify(state.toJSON()))}
/>

<RichTextView value={storedEditorStateJSON} />
```

## Validation

- `pnpm -F @astryxdesign/lab typecheck` — clean (against real Lexical 0.46 types)
- `pnpm exec vitest run RichTextEditor` — 11/11 tests pass
- `eslint src/RichTextEditor` — clean
- `check:changesets`, `sync-exports:check` — pass (no changeset: lab is private/canary-only)

http://localhost:6006/?path=/story/lab-richtexteditor--with-description

https://github.com/user-attachments/assets/91ff5f65-b190-4e0a-811e-4049ebac65c1

## Files

```
packages/lab/src/RichTextEditor/
  RichTextEditor.tsx        # editor component
  RichTextView.tsx          # read-only renderer
  editorTheme.ts            # shared StyleX → Lexical theme mapping
  index.ts                  # component entry
  RichTextEditor.test.tsx   # colocated tests (11)
  RichTextEditor.doc.mjs    # component docs
packages/lab/src/index.ts               # barrel re-export (RFC-referenced)
packages/lab/package.json               # optional Lexical peers
apps/storybook/stories/RichTextEditor.stories.tsx
```

## Context

OSS foundation for replacing Meta-internal EPS-Lexical primitives with an Astryx-based editor. The Meta-coupled pieces (intern mentions, entity hover cards, write-with-AI, Relay/analytics) stay internal and compose on top via the `nodes`/`plugins` extension points — intentionally **not** part of this PR.

---
*Companion to RFC #3899.*

### CODE REVIEW

**Comment by potatowagon** [comment]
Note on the failing `test` check — it looks unrelated to this PR:

- The failure is in `packages/cli/src/commands/build-theme.watch.test.mjs` → *"builds initially, rebuilds on change, and stops cleanly on SIGINT"* (`expected false to be true` at line 131, the `/rebuild/i` stdout assertion).
- This PR touches only `packages/lab/` (the RichTextEditor component), the storybook story, `packages/build/src/next.js`, and the lockfile — **no changes to `packages/cli/`**.
- The test spawns `astryx theme build --watch` as a child process, edits a theme file, and polls up to an 8s timeout for a chokidar rebuild. In the run it failed at ~8.6s — right at the `waitFor` ceiling — which is the signature of a load-induced timing flake under the full ~6,300-test parallel suite.
- It **passes in isolation** (`vitest run build-theme.watch` → 3/3, ~0.7s) and passed on earlier CI runs of this same branch.

The RichTextEditor's own tests pass (11/11), and `build`, `build-sandbox`, `build-storybook`, `lint`, `smoke-test`, and `docsite-test` are green.

Happy to help if maintainers believe it's not a flake — I didn't want to touch an unrelated CLI test from a component PR. A re-run of the `test` job would likely confirm.

**Review by humbertovirtudes — COMMENTED** [review]
Reviewing as an RFC companion, not as a merge gate (the description says it's not requesting merge yet). The architecture is solid: Lexical as optional peer deps keeps core's zero-dep promise intact, the StyleX-token theme is shared between editor and view so they render identically, the `nodes`/`plugins` extension points let consumers layer mentions/toolbars without forking, and the a11y wiring (role=textbox, aria-multiline, labelledby/describedby, required/invalid) is careful. Helper components are at module scope, tests are colocated, and the doc + story are present.

A few things to reconcile before this graduates past RFC:

**1. (major) The changeset contradicts the `next.js` implementation.** The changeset for `@astryxdesign/build` says the `source` condition is now "applied via a scoped `module.rules` entry that only matches `node_modules/@astryxdesign/*`" (an allowlist). The code does the opposite: `config.resolve.conditionNames` stays global with `source` first, and the unshifted rule *excludes* `lexical|@lexical/*|yjs` (a blocklist). Two consequences: the published `@astryxdesign/build` changelog will be factually wrong, and the blocklist is the more fragile design: the next third-party dep that ships a `source` export re-breaks the same way, whereas the allowlist the changeset describes would be robust. Worth reconciling the two, and preferring the allowlist if React JSX resolution allows it (the comment hints it may not, which would be good to confirm and capture).

**2. (minor) CI `test` is red, but on an unrelated test.** The failure is `packages/cli/src/commands/build-theme.watch.test.mjs` ("expected false to be true" on a watch-rebuild timing assertion), with 6341/6342 passing. It doesn't touch anything this PR changes and looks like a watch-mode timing flake under a heavy CI install. A re-run should confirm; if it persists it's a pre-existing flake rather than this change.

**3. (minor) Needs a rebase.** Currently shows conflicts with main (the description notes an in-flight FieldStatus PR on the same files).

**4. (minor) `RichTextView` error handling on the read path.** `onError` re-throws. A read-only view renders *persisted* JSON, which is exactly where stale or foreign-schema state tends to show up, and a bad `value` would throw during render and can take down the host. Consider a fallback or a documented error-boundary contract for the view specifically.

**5. (minor) `RichTextView` has a single test** and no coverage for its `nodes`/`plugins`/`namespace` extension points or malformed input.

Nits: `yjs` in the exclusion regex is speculative (it only arrives transitively via `@lexical/react`), `initialConfig` is rebuilt every render though `LexicalComposer` only reads it on mount (harmless), and the package.json diff swaps literal em-dashes for `\u2014` escapes, which is unrelated churn.

The headline is #1: the changeset and code disagree about a shared build package. Everything else is polish.

**Comment by potatowagon** [comment]
Thanks for the thorough review @humbertovirtudes — really helpful. Addressed all five, pushed as two clean commits (rebased onto latest `main`).

**#1 (major) — changeset ↔ code reconciled, and switched to the allowlist.** You were right on both counts: the changelog was factually wrong, and the blocklist was the fragile design. I've moved to the **allowlist** the changeset described. The reason I'd originally reached for the blocklist was that my first allowlist attempt broke React JSX (`(0, d.jsxDEV) is not a function`) — but that was because I was *replacing* the global `config.resolve.conditionNames` (dropping Next's `'...'` sentinel + `react-server`). The fix is to leave the global conditions alone and scope `source` via a `module.rules` entry that *augments* rather than replaces:

```js
config.module.rules.unshift({
  test: /[\\/]node_modules[\\/]@astryxdesign[\\/]/,
  resolve: { conditionNames: ['source', '...'] },  // '...' inherits Next's defaults
});
```

Verified the sandbox `next build` compiles cleanly with this (no `declare`/`jsxDEV` errors, lexical resolves to built JS). The changeset now describes exactly this. This is robust to the next third-party dep that ships a `source` export.

**#2 (minor) — `test` flake.** Agreed it's unrelated (`build-theme.watch.test.mjs`, watch-rebuild timing under heavy CI). It passes in isolation (3/3, ~0.7s). Didn't touch it — a re-run should clear it.

**#3 (minor) — rebased** onto latest `main`; conflicts resolved (clean rebase, no remaining conflicts).

**#4 (minor) — `RichTextView` read-path error handling.** Good call — a read-only view renders persisted/foreign JSON, exactly where bad state shows up. It no longer re-throws: malformed JSON (or state with unregistered node types) now renders an optional `errorFallback` and calls a new `onParseError` callback instead of throwing during render and taking down the host. `value` is JSON-validated before it reaches `LexicalComposer` (a parse throw during init would otherwise escape the error boundary), and the Lexical `onError` routes to the same fallback path. State recovers when a corrected `value` comes in.

**#5 (minor) — `RichTextView` tests.** Added coverage for `plugins`, `namespace`, extra `nodes`, malformed-JSON → fallback + `onParseError`, and the no-fallback path. 11 → 16 tests, all green.

**Nits:**
- `yjs` was in the old blocklist regex — the allowlist removes the need for that speculative entry entirely, so it's gone.
- `initialConfig` rebuilt each render — left as-is per your note that it's harmless (`LexicalComposer` reads it only on mount); happy to memoize if you'd prefer.
- package.json em-dash/`\u2014` churn — that was in the auto-generated lockfile region, not hand-authored; the component `package.json` diff is just the optional Lexical peers.

**Review by cixzhang — APPROVED** [review]

File: packages/lab/package.json [hunk 1]
```diff
@@ -59,15 +59,58 @@
...
+    "@lexical/react": "^0.46.0",
+    "@lexical/rich-text": "^0.46.0",
+    "@lexical/utils": "^0.46.0",
+    "@types/d3-array": "^3.2.2",
     "@types/d3-scale": "^4.0.9",
-    "@types/d3-shape": "^3.1.8"
+    "@types/d3-shape": "^3.1.8",
+    "lexical": "^0.46.0"
+  },
+  "peerDependenciesMeta": {
```
Comment (cixzhang) [inline packages/lab/package.json:90]: We can clean these up :)
