### PR TITLE
fix(deps): align workspace on single vite 7, drop vite override

### PR DESCRIPTION
**Pull request by Han5991**
## Summary

Fixes the root `vitest.config.ts` type break (TS2769) introduced by #3838 by aligning the whole workspace on a single vite version and removing the `vite` override.

### Root cause

#3838 bumped vite 6.4.3 → 8.1.3 in the two vite example apps only. The workspace override (`vite: ^6.4.3`) does not clamp direct dependencies under pnpm 11, so the lockfile ended up carrying **both** vite 6.4.3 and 8.1.3. The root project declares no vite of its own, so `@vitejs/plugin-react` auto-peer-resolved against 8.1.3 while `vitest/config` (vitest 2.1.9) stayed on 6.4.3 — two structurally incompatible `Plugin` types (vite 8 changed the `hotUpdate` hook context), hence:

```
vitest.config.ts(26,5): error TS2769: No overload matches this call.
  ... Type 'import(".../@vitejs/plugin-react/node_modules/vite/...").Plugin<any>'
      is not assignable to type 'import(".../node_modules/vite/...").Plugin<any>'.
```

vite 8 is also outside `@vitejs/plugin-react` 4.x's peer range (`^4.2 || ^5 || ^6 || ^7`), so the bumped combination was never actually supported.

### Fix — one vite, no override

- **vitest `^2.1.0` → `^3.2.1`** (+ `@vitest/coverage-v8`): vitest 3's own vite range covers 7.x, and `apps/docsite` is already on vitest 3.
- **The vite version is pinned once in the pnpm `catalog`** (`vite: ^7.3.6`, the top of plugin-react 4.x's peer range); the root project and both example apps declare `"vite": "catalog:"`. All resolvers converge on a single `vite@7.3.6`, and since dependabot updates pnpm catalog entries atomically, a future bump moves every consumer together instead of splitting the workspace the way #3838 did.
- **Drop the `vite: ^6.4.3` override.** Its remaining job was lifting vitest 2's internal `vite@^5` dependency up to 6.4.3 so plugin-react and vitest shared one vite instance — verified by removing the override alone under vitest 2, which reproduces the same TS2769 (vite 5.4.21 vs 6.4.3). vitest 3 makes it unnecessary.
- `scripts/build-css.test.mjs`: `await` a hanging `expect().resolves` that vitest 3 reports as deprecated.

### Verification

- `tsc --noEmit`: `vitest.config.ts` / `vitest.workspace.ts` clean; full error set diffed against `main` — no new errors.
- Full suite on vitest 3.2.6: **332 test files / 6,177 tests pass.**
- Both example apps build with vite 7.3.6.
- `pnpm peers check`: no vite-related peer issues; the lockfile contains a single `vite@7.3.6`.
- Peer ranges of all vite consumers checked: `@vitejs/plugin-react` 4.7 (≤7), `@storybook/builder-vite` 10.4.6 (≤8), `@stylexjs/unplugin` (≤8), `vite-plugin-singlefile` (≤8).

### Follow-up (after this PR merges)

Once this lands, a follow-up PR will raise the catalog pin to **vite `^8.1.3` and align vitest with it in the same pass**: vitest 4 + `@vitest/coverage-v8` 4 + `@vitejs/plugin-react` 5, including the `vitest.workspace.ts` → `test.projects` migration that vitest 4 requires. This PR intentionally stops at vite 7 so the toolchain upgrade stays verifiable in one step; until the follow-up lands, catalog-wide vite-major bumps should be held back since plugin-react 4.x cannot follow.

### CODE REVIEW

File: apps/example-vite-tailwind/package.json [hunk 1]
```diff
@@ -21,7 +21,7 @@
     "@vitejs/plugin-react": "^4.3.0",
     "tailwindcss": "^4",
     "typescript": "^6.0.3",
-    "vite": "^8.1.3"
+    "vite": "catalog:"
```
Comment (cixzhang) [inline apps/example-vite-tailwind/package.json]: For these examples, we're never really building them within the repo but they serve as example apps for the community to copy. I guess updating to catalog here means that they'd have to go in and update it again. For the purpose these examples serve, I'm wondering if it makes more sense to exclude them from the pnpm workspace instead?

**Review by cixzhang — CHANGES_REQUESTED** [review]

File: apps/example-vite-tailwind/package.json (hunk 1 above)
Comment (Han5991) [reply apps/example-vite-tailwind/package.json]: If you call it a template, then that would be correct!

**Review by cixzhang — APPROVED** [review]
Thanks for updating this!

**Review by cixzhang — APPROVED** [review]
